name = "backend"
compatibility_date = "2023-12-01"

[vars]

DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiY2FlNjA2NWItNWE3NC00ODc2LWJhNjMtYzRhZTQyMWIwMmY1IiwidGVuYW50X2lkIjoiNjgyZTk5ZWQxMWZhNzQxYzhjOWQ0ZmU5MWQ3N2RkNmFhOTg1ZDE0ODY0M2M0ZWUwOTM5MjNiZTAwYmU5NzQ0OCIsImludGVybmFsX3NlY3JldCI6IjE5ZGZmNjdlLTY1ZjctNDBmZC04ZDVlLWM3Y2VmNTM2MWExMCJ9.-CGS7CZe3mBVj5tb7L-7EhK2cSH6iiWjEGLxvPWqQPA"

JWT_SECRETE = "secrete"